### ISSUE TITLE
NiftyNet should be able to connect to an XNAT instance to fetch data

### ISSUE THREAD

**Issue by tvercaut** [NifTK/NiftyNet#184] opened 2018-07-31 18:51 UTC
As discussed with @atbenmurray, rather than alway working from images "dumped" in a folder, it would be great for NiftyNet to support training from data stored on an XNAT server. This will pose a number of questions related to authentication and IO bottlenecks which in the long run would need to be solved.

As a side note, I am referring to an [old issue on cmiclab, #205](https://cmiclab.cs.ucl.ac.uk/CMIC/NiftyNet/issues/205) which had some interesting comments on IO efficiency when working with 2D images.

**Comment by ericspod** [comment] 2019-05-28 17:27
This is essentially a duplicate of #183.

**Closed by ericspod** 2019-05-28 17:27 UTC

**Comment by tvercaut** [comment] 2019-05-29 13:42
This is actually not really a duplicate. #183 is about one-off downloading through a command-line whereas #184 is a tighter integration at the API level.
