### ISSUE TITLE
Label issue for Classification task

### ISSUE THREAD

**Issue by Kyuuki93** [NifTK/NiftyNet#42] opened 2018-01-30 13:31 UTC
How to use  scalar e.g. 0 and 1 as label for classification task? 
I looked up the documentation,  but didn't find an example.
thanks

**Comment by wyli** [comment] 2018-01-30 13:38
HI @Kyuuki93  The classification application has been implemented recently but the documentation is still work in progress, it'll be available in the next release (v0.3).

**Comment by Kyuuki93** [comment] 2018-01-30 13:55
Great work, which format should label data saved in?

**Comment by eligibson** [comment] 2018-01-31 08:47
Currently, you can load labels by making them 1x1x1 images, but set interp_order to -1 in the config file. We are still working out what formats to support for labels, so if you have preferences, please let us know.

**Comment by Kyuuki93** [comment] 2018-02-01 15:54
@wyli @eligibson 
I finished the training according to your suggestion，the dataset include some MR images download from OASIS.
There are two flaws in INFERENCE stage:
1)  the prediction result will be saved in a .nii file, it's not so convenient to evaluate the accuracy, like this
`INFO:niftynet: Inference iter 2,  (0.045657s)
...... (1, 1)
Saved /home/*/NiftyNet/models/tstnet/output/tstnet/S007_niftynet_out.nii.gz
INFO:niftynet: Inference iter 3,  (0.040947s)
...... (1, 1)
Saved /home/*/NiftyNet/models/tstnet/output/tstnet/S020_niftynet_out.nii.gz
`
2) the `output_prob` parameter in [CLASSIFICATION] section must be `False`, otherwise will throw `ValueError: cannot reshape array of size 2 into shape (1,1,1,1,1)`,  the error should come from the label format

**Comment by eligibson** [comment] 2018-02-01 16:11
1) I agree that output as nii files is not ideal. We are working on that in two ways. First, we are adding built in tools for evaluation. Second, we are planning to revamp the IO to allow other ways to specify labels and get the outputs. Some of this will be ready for the next release. 

Until then, it is fairly straightforward to write a short python script to go through the nii files and add the output to a csv file:

import nibabel, glob
with open('output.csv','w') as f:
  for fn in glob.glob('*_niftynet_out.nii.gz'):
    f.write('%s,%i\n'%(fn.replace('_niftynet_out.nii.gz',''), nibabel.load(fn).get_data()[0,0,0,0,0]))


2) This looks like a bug. I'll add an issue and get it fixed.

**Comment by eligibson** [comment] 2018-02-08 15:54
These should both be resolved by commit 0f4ac8485ce477c6c1fc308cbfb77b4c30482ecb
Classification now outputs a csv file in addition to the nii files.

**Closed** 2018-03-07 16:48 UTC

**Comment by andys0975** [comment] 2018-08-05 08:53
So... I wonder now we still need to use 1x1x1 images as label's format ?
Is there a method to use pandas to read the labels for Classification & Regression task ?

**Comment by koriavinash1** [comment] 2019-06-06 21:32
@Kyuuki93 can you share your config file?
