### ISSUE TITLE
Proposition of New Logo Design for NifftyNet

### ISSUE THREAD

**Issue by Colmena-PM** [NifTK/NiftyNet#59] opened 2018-02-27 13:59 UTC
hello a lot of pleasure and good day is a pleasure to be able to offer my support with my designs.

This proposal is made through the Steemit network in Utopian, a totally free project, You dont have to agree on anything or anything.

https://steemit.com/utopian-io/@colmena-powmax/logo-designs-for-niftynet

![nifftynet](https://user-images.githubusercontent.com/36889309/36732387-fb96c9d2-1ba3-11e8-8cea-657aff76cc4b.jpg)

**Comment by tvercaut** [comment] 2018-02-27 14:39
Thank you for the proposal. I am closing this issue as a duplicate of #48 where it will be taken into account.

We are discussing about changing the logo so it's great to have a number of suggestions to work with.

**Closed by tvercaut** 2018-02-27 14:39 UTC
