### ISSUE TITLE
For different data size:Provided indices are out-of-bounds w.r.t. dense side with broadcasted shape

### ISSUE THREAD

**Issue by ChenxiCui97** [NifTK/NiftyNet#204] opened 2018-08-11 01:29 UTC
hello,
I use the `>net_segment train -c E:\Abinaya\codes\vnet_dense2d.ini` to train the model. and I have set the interp_order = 0 for label. The num_classes= 2.when I input the data with(200,400, 2096) It seems work. But we i input (200,400,512) or(200,400,1024). It cause error 
```python-traceback
INFO:niftynet: starting from iter 0
INFO:niftynet: Parameters from random initialisations ...
INFO:niftynet: Filling queues (this can take a few minutes)
INFO:niftynet: Starting preprocessing threads...
INFO:niftynet: New thread: 0
INFO:niftynet: New thread: 1
INFO:niftynet: iter 0, dice_loss=0.5614714622497559 (28.336s)
INFO:niftynet: Cleaning up...
INFO:niftynet: iter 1 saved: C:\Users\Neurotoolbox\models\densevnet2d\models\model.ckpt
INFO:niftynet: stopping sampling threads
INFO:niftynet: SegmentationApplication stopped (time in second 60.28).
Traceback (most recent call last):
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_call
    return fn(*args)
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1329, in _run_fn
    status, run_metadata)
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Provided indices are out-of-bounds w.r.t. dense side with broadcasted shape
         [[Node: worker_0/loss_function/mul = SparseDenseCwiseMul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](worker_0/loss_function/stack, worker_0/loss_function/ones_like, worker_0/loss_function/ToInt64_2, worker_0/loss_function/Softmax)]]
         [[Node: worker_0/loss_function/mul_1/_375 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_3364_worker_0/loss_function/mul_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\neurotoolbox\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\neurotoolbox\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Neurotoolbox\Anaconda3\Scripts\net_segment.exe\__main__.py", line 9, in <module>
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\niftynet\__init__.py", line 55, in main
    app_driver.run_application()
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\niftynet\engine\application_driver.py", line 164, in run_application
    self._training_loop(session, loop_status)
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\niftynet\engine\application_driver.py", line 326, in _training_loop
    graph_output = sess.run(vars_to_run)
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1344, in _do_run
    options, run_metadata)
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Provided indices are out-of-bounds w.r.t. dense side with broadcasted shape
         [[Node: worker_0/loss_function/mul = SparseDenseCwiseMul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](worker_0/loss_function/stack, worker_0/loss_function/ones_like, worker_0/loss_function/ToInt64_2, worker_0/loss_function/Softmax)]]
         [[Node: worker_0/loss_function/mul_1/_375 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_3364_worker_0/loss_function/mul_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'worker_0/loss_function/mul', defined at:
  File "c:\users\neurotoolbox\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\neurotoolbox\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Neurotoolbox\Anaconda3\Scripts\net_segment.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\niftynet\__init__.py", line 55, in main
    app_driver.run_application()
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\niftynet\engine\application_driver.py", line 143, in run_application
    self.graph = self._create_graph()
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\niftynet\engine\application_driver.py", line 220, in _create_graph
    self.gradients_collector)
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\niftynet\application\segmentation_application.py", line 243, in connect_data_and_network
    weight_map=data_dict.get('weight', None))
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\niftynet\layer\base_layer.py", line 32, in __call__
    return self._op(*args, **kwargs)
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\tensorflow\python\ops\template.py", line 273, in __call__
    result = self._call_func(args, kwargs, check_for_new_variables=False)
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\tensorflow\python\ops\template.py", line 222, in _call_func
    result = self._func(*args, **kwargs)
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\niftynet\layer\loss_segmentation.py", line 61, in layer_op
    pred, ground_truth, weight_map))
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\niftynet\layer\loss_segmentation.py", line 320, in dice
    one_hot * prediction, reduction_axes=[0])
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py", line 918, in binary_op_wrapper_sparse
    name=name), sp_x.dense_shape)
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\tensorflow\python\ops\gen_sparse_ops.py", line 1188, in sparse_dense_cwise_mul
    sp_shape=sp_shape, dense=dense, name=name)
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3160, in create_op
    op_def=op_def)
  File "c:\users\neurotoolbox\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Provided indices are out-of-bounds w.r.t. dense side with broadcasted shape
         [[Node: worker_0/loss_function/mul = SparseDenseCwiseMul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](worker_0/loss_function/stack, worker_0/loss_function/ones_like, worker_0/loss_function/ToInt64_2, worker_0/loss_function/Softmax)]]
         [[Node: worker_0/loss_function/mul_1/_375 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_3364_worker_0/loss_function/mul_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
```

I saw some people who have this problem will set  interp_order into 0. I have done the same thing.But it cannot work.
Could you help to solve the problems?
Thanks!!!

**Comment by ChenxiCui97** [comment] 2018-08-11 01:39
well. sometimes for the data(200,400,2096) it  also cannot work, It is weird.

**Comment by wyli** [comment] 2018-08-11 15:03
Hi @ChenxiCui97  looks like you have corrupted training labels

if they are in nifti format you can check the label files:
```python
import nibabel
import numpy as np
uniq_labels = None
for f_name in label_files:
    print('file name: {}'.format(f_name))

    uniq = np.unique(nibabel.load(f_name).get_data())
    if uniq_labels is None:
        uniq_labels = uniq
        assert len(uniq_labels) == 2, 'should be binary labels'
    assert np.all(uniq == uniq_labels), 'should have consistent labels'
```

**Comment by ChenxiCui97** [comment] 2018-08-13 17:41
Hi @wyli ,
Thanks for your help. Your are right! One of the label file is not in binary. By the way, when the segment model has run about 1600 iteration. It shows that the memory of the GPU is full. Do you know hoe to handle it ? Thanks very much.

**Comment by ericspod** [comment] 2019-05-29 12:34
Is it actually filling memory such that the program fails? Tensorflow allocates all memory at once so it always looks full. If it is failing then it's a memory leak somehow we need to investigate.

**Comment by wyli** [comment] 2019-06-06 16:24
I'm closing this now, please reopen if exact steps to reproduce the issue is available.

**Closed by wyli** 2019-06-06 16:24 UTC
Labels: bug
