### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by YilinLiu97** [NifTK/NiftyNet#126] opened 2018-06-17 16:03 UTC
Hi, I'm wondering when can we expect to use the evaluation package? thanks!

**Comment by YilinLiu97** [comment] 2018-06-28 06:11
it would be super helpful if we can use the evaluation package! Thanks!

**Comment by anlarro** [comment] 2018-07-17 10:51
Also, when I run evaluation for a segmentation application. I have 3 labels (0,1,2) but I only get results for label 1 and label 2.

subject_id | label | average_distance | dice | jaccard
patient_001 | 1 | 4.125.553.053.793.350 | 0.9189724245002907 | 0.8500915659579655
patient_001 | 2 | 9.440.353.070.706.600 | 0.260731080152343 | 0.14990843404203447
patient_002 | 1 | 4.471.972.883.082.370 | 0.9218043297008649 | 0.854950873105546
patient_002 | 2 | 1.009.666.179.638.670 | 0.25335005020762585 | 0.14504912689445404

**Comment by wyli** [comment] 2018-09-11 13:47
duplicate of https://github.com/NifTK/NiftyNet/issues/94

**Closed by wyli** 2018-09-11 13:47 UTC
